name: Update plugin.zip in plugins

on:
  push:
    paths:
      - 'plugins/**'

jobs:
  update-plugin-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip files (excluding plugin.zip) and replace plugin.zip
        run: |
          cd plugins
          for d in */ ; do
            cd "$d"
            zip -r temp.zip * -x plugin.zip
            mv temp.zip plugin.zip
            cd ..
          done

      - name: Move plugin.zip to plugins folder
        run: |
          cd plugins
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add */plugin.zip
          git commit -m "Update plugin.zip"
          git push
